site_name: Отчеты по лабораторным работам. Ермаков Максим, K3340

theme:
  name: readthedocs
  language: ru
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 'Главная': 'index.md'
  - 'Лабораторная работа №1':
    - 'Задание 1: UDP Клиент-Сервер': 'task1.md'
    - 'Задание 2: TCP: площадь параллелограмма': 'task2.md'
    - 'Задание 3: HTTP Сервер': 'task3.md'
    - 'Задание 4: TCP Чат': 'task4.md'
    - 'Задание 5: Веб-сервер (GET/POST)': 'task5.md'